sudo: required

services:
  - docker

env:
  - NODE_VERSION=latest
  - NODE_VERSION=lts
  - NODE_VERSION=old
  - PHP_VERSION=5.6
  - PHP_VERSION=7.0

script:
  - make build-$PHP_VERSION-$NODE_VERSION
  - make test-all-$PHP_VERSION-$NODE_VERSION

deploy:
  provider: script
  script: docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make push-$PHP_VERSION-$NODE_VERSION
  on:
    repo: 'umweltdk/docker-php'
    branch: master
